version: "2.2"

services:
  db:
    image: rahulbharuka/postgres-db:v1
    ports:
      - ${DB_PORT}:5432
    init: true
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    restart: always

  comment-app:
    image: rahulbharuka/comment-app:v1
    ports:
      - 6060:6060
    environment:
      - PORT=6060
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}      
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    command: ./main
    depends_on:
      - db
    links:
      - db

  member-app:
    image: rahulbharuka/member-app:v1
    ports:
      - 7070:7070
    environment:
      - PORT=7070 
    command: ./main